from pathlib import Path
p=Path('research/research-state.yaml'); s=p.read_text(encoding='utf-8')
# mark hypothesis statuses based on survey
s=s.replace('  - id: H1\n    statement: "Mature OGCM robustness comes more from conservative finite-volume/finite-element operators, split-explicit time stepping, and disciplined boundary masks than from exotic high-order stencils."\n    status: pending', '  - id: H1\n    statement: "Mature OGCM robustness comes more from conservative finite-volume/finite-element operators, split-explicit time stepping, and disciplined boundary masks than from exotic high-order stencils."\n    status: supported')
s=s.replace('  - id: H2\n    statement: "The dominant production ocean models use a small set of proven subgrid closures (GM/Redi, KPP, Smagorinsky/biharmonic) rather than model-specific ad hoc schemes."\n    status: pending', '  - id: H2\n    statement: "The dominant production ocean models use a small set of proven subgrid closures (GM/Redi, KPP, Smagorinsky/biharmonic) rather than model-specific ad hoc schemes."\n    status: supported')
s=s.replace('  - id: H3\n    statement: "Modern scalability is increasingly achieved through MPI domain decomposition with optional GPU/accelerator ports rather than monolithic JAX-style whole-step compilation."\n    status: pending', '  - id: H3\n    statement: "Modern scalability is increasingly achieved through MPI domain decomposition with optional GPU/accelerator ports rather than monolithic JAX-style whole-step compilation."\n    status: partially_supported')
s=s.replace('  - id: H4\n    statement: "The most transferable next improvements are conservative horizontal transport, robust vertical coordinate treatment, and standardized diagnostics, not immediate neural-PDE extensions."\n    status: pending', '  - id: H4\n    statement: "The most transferable next improvements are conservative horizontal transport, robust vertical coordinate treatment, and standardized diagnostics, not immediate neural-PDE extensions."\n    status: supported')
p.write_text(s,encoding='utf-8')
print(s)
