#!/bin/bash
set -euo pipefail
cd /mnt/c/Users/zhen.luo/ocean_solver

# Launch the pre-registered cooling_ice candidate only after the MOM6 annual
# comparison has produced its gate JSON. The inner script performs the same
# existence check as a second guard.
while [ ! -f research/experiments/industrial_comparison_045/mom6_stage_f_dynamic_365d_v12_gate.json ]; do
  sleep 300
done

bash scripts/run_stage_f_cooling_ice_365d.sh

OUT=research/experiments/industrial_comparison_045
NPZ=/root/external_models/results/industrial_comparison_045/global_global_stage_f_dyn_ice_band40_65_mld100_lat40_60_cooling_ice_gate_365d.npz
SNAP=/root/external_models/results/industrial_comparison_045/global_global_stage_f_dyn_ice_band40_65_mld100_lat40_60_cooling_ice_gate_365d_3d

python3 src/benchmark_metrics.py --npz /root/external_models/results/industrial_comparison_045/global_global_stage_f_dyn_ice_band40_65_mld100_lat40_60_cooling_ice_gate_365d.npz --out research/experiments/industrial_comparison_045/global_global_stage_f_dyn_ice_band40_65_mld100_lat40_60_cooling_ice_gate_365d_benchmark.json --steady-days 90

python3 src/score_solver_3d.py --npz /root/external_models/results/industrial_comparison_045/global_global_stage_f_dyn_ice_band40_65_mld100_lat40_60_cooling_ice_gate_365d.npz --snap-dir /root/external_models/results/industrial_comparison_045/global_global_stage_f_dyn_ice_band40_65_mld100_lat40_60_cooling_ice_gate_365d_3d --snap-days 30 --steady-days 90 --out research/experiments/industrial_comparison_045/global_global_stage_f_dyn_ice_band40_65_mld100_lat40_60_cooling_ice_gate_365d_3d_benchmark.json

python3 src/benchmark_gate.py --control research/experiments/industrial_comparison_045/ocean_solver_stage_f_365d_3d_surface_benchmark.json --experiment research/experiments/industrial_comparison_045/global_global_stage_f_dyn_ice_band40_65_mld100_lat40_60_cooling_ice_gate_365d_benchmark.json --control-3d research/experiments/industrial_comparison_045/ocean_solver_stage_f_365d_3d_benchmark.json --experiment-3d research/experiments/industrial_comparison_045/global_global_stage_f_dyn_ice_band40_65_mld100_lat40_60_cooling_ice_gate_365d_3d_benchmark.json --days 365 --require-3d --out research/experiments/industrial_comparison_045/global_global_stage_f_dyn_ice_band40_65_mld100_lat40_60_cooling_ice_gate_365d_gate.json
